{
  "hash": "2a5d8bbd6af7afdea26072b779379c7a",
  "result": {
    "engine": "jupyter",
    "markdown": "# Scattering {#sec-scattering}\n\n[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/{{< var github_user >}}/{{< var repo >}}/blob/main/{{< var subdir >}}/notebooks/scattering.ipynb){.colab-link} &nbsp;Run this chapter's code in Google Colab (no installation).\n\n\n*Slides 277–288: Rayleigh scattering ($\\propto\\lambda^{-4}$), attenuation, fiber loss mechanisms, optical time-domain reflectometry,\nspontaneous Raman scattering, spontaneous and stimulated Brillouin scattering. Chapter 2 develops the fiber side (loss spectrum,\nOTDR, distributed sensors) in detail.*\n\n## Key relations\n\nA particle much smaller than the wavelength is polarised by the field and re-radiates as an oscillating dipole, in \"many\"\ndirections (slide 277). The scattered power grows as $\\lambda^{-4}$, and its angular pattern for unpolarised light is\n$\\propto1+\\cos^2\\theta$. A beam crossing a scattering medium is attenuated (slides 279–281):\n\n$$\nI=I_0e^{-\\alpha_Rz},\\qquad \\alpha_R\\propto\\frac{1}{\\lambda^4},\\qquad\n\\alpha_\\text{dB}=\\frac{10}{L}\\log_{10}\\frac{P_\\text{in}}{P_\\text{out}}=4.34\\,\\alpha .\n$$\n\n| inelastic process | origin | shift in silica | use |\n|---|---|---|---|\n| Raman | molecular vibrations (optical phonons) | ≈ 13 THz (≈ 100 nm at 1550 nm) | distributed temperature sensing, Raman amplifiers |\n| Brillouin | acoustic waves (acoustic phonons) | $\\nu_B=2nv_a/\\lambda\\approx11$ GHz | strain and temperature sensing; SBS limits launch power |\n\n### Why the sky is blue, live\n\n```{ojs}\n//| echo: false\nviewof ry = Inputs.range([380, 750], {value: 450, step: 1, label: \"wavelength (nm)\"})\n```\n\n```{ojs}\n//| echo: false\n{\n  const data = d3.range(380, 751, 2).map(l => ({l, s: (550/l)**4}));\n  const col = l => d3.interpolateTurbo(0.08 + 0.84*(l - 380)/370);\n  return Plot.plot({\n    width: Math.min(width, 1050), height: 260, x: {label: \"λ (nm)\"}, y: {label: \"Rayleigh scattering relative to 550 nm\", grid: true},\n    marks: [Plot.rectY(data, {x1: d => d.l - 1, x2: d => d.l + 1, y: \"s\", fill: d => col(d.l)}),\n            Plot.ruleX([ry], {stroke: \"#0b0b0b\", strokeWidth: 2})]\n  });\n}\n```\n\n```{ojs}\n//| echo: false\nhtml`<div class=\"result-box\">At ${ry} nm light is scattered ${((550/ry)**4).toFixed(2)}× as strongly as at 550 nm, and\n${((700/ry)**4).toFixed(1)}× as strongly as deep red (700 nm). Blue dominates the scattered skylight; the transmitted sunset light is red.</div>`\n```\n\n## Worked example: the Rayleigh floor of fiber loss (slides 279–281)\n\nThe Rayleigh contribution is $\\alpha_R=A/\\lambda^4$. The coefficient $A$ depends on the glass composition and fabrication; here\n$A\\approx0.8$ dB km⁻¹ µm⁴ is a representative value (Chapter 2 derives it from the glass properties).\n\n::: {#cell-fig-rayleigh .cell execution_count=2}\n``` {.python .cell-code}\nA = 0.8\nlam_um = np.linspace(0.8, 1.7, 400)\nbands = {\"O\": (1260, 1360), \"E\": (1360, 1460), \"S\": (1460, 1530), \"C\": (1530, 1565), \"L\": (1565, 1625), \"U\": (1625, 1675)}\nfig = plt.figure(figsize=(11, 3.8))\nax = fig.add_subplot(1, 2, 1)\nax.semilogy(lam_um*1e3, A/lam_um**4, label=\"Rayleigh floor A/λ⁴\")\nfor k, (b, (l1, l2)) in enumerate(bands.items()):\n    ax.axvspan(l1, l2, alpha=0.1, color=ol.PALETTE[k % 8], lw=0); ax.text((l1 + l2)/2, 2.2, b, ha=\"center\", color=ol.INK2)\nax.set(xlabel=\"λ (nm)\", ylabel=\"α (dB/km)\", ylim=(0.1, 3)); ax.legend()\naxp = fig.add_subplot(1, 2, 2, projection=\"polar\")\nth = np.linspace(0, 2*np.pi, 400)\naxp.plot(th, 1 + np.cos(th)**2); axp.set_title(\"scattered intensity vs angle\", fontsize=10)\nplt.tight_layout(); plt.show()\nfor l in (0.85, 1.31, 1.55):\n    print(f\"{l*1e3:.0f} nm: α_R ≈ {A/l**4:.2f} dB/km\")\n```\n\n::: {.cell-output .cell-output-display}\n![Rayleigh scattering loss in a silica fiber across the telecom bands, and the dipole scattering pattern (1 + cos²θ) for unpolarised light.](scattering_files/figure-html/fig-rayleigh-output-1.png){#fig-rayleigh width=1095 height=406}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n850 nm: α_R ≈ 1.53 dB/km\n1310 nm: α_R ≈ 0.27 dB/km\n1550 nm: α_R ≈ 0.14 dB/km\n```\n:::\n:::\n\n\nAt long wavelengths, infrared absorption of Si–O bonds (the IR resonance of @sec-index) takes over. The crossing of the two\nmechanisms places the loss minimum near 1550 nm.\n\n## Worked example: a toy OTDR trace (slides 282–283)\n\nAn OTDR launches a short pulse and records the Rayleigh backscatter versus time $t$, that is distance $z=v_gt/2$. The trace falls\nwith slope $2\\alpha$ (round trip), displayed as $\\alpha$ in dB/km after the conventional 5·log₁₀ scaling. Splices appear as steps\nand connectors or fiber ends as Fresnel reflection peaks. Chapter 2 has a live OTDR simulator.\n\n::: {#cell-fig-otdr .cell execution_count=3}\n``` {.python .cell-code}\nrng = np.random.default_rng(1)\nNg_f, tau = 1.468, 100e-9\ndz = c0*tau/(2*Ng_f)\nz = np.arange(0, 30e3, 2.0)\nloss = 0.20/1e3*z + 0.15*(z > 8e3) + 0.5*(z > 15e3)\nlin = np.where(z <= 25e3, 10**(-loss/10), 0.0)\nfor z0, hgt in {15e3: 14, 25e3: 18}.items():\n    lin += 10**((-np.interp(z0, z, loss) + hgt)/10)*np.exp(-((z - z0)/dz)**2)\nlin += 10**(-12/10)\ntrace = 10*np.log10(lin) + 0.05*rng.standard_normal(z.size)*(1 + (z/10e3)**2)\nfig, ax = plt.subplots(); ax.plot(z/1e3, trace, lw=0.7)\nax.set(xlabel=\"distance (km)\", ylabel=\"relative level (dB)\", title=f\"resolution ≈ {dz:.0f} m\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Toy OTDR trace: a 25 km fiber with a splice at 8 km, a connector at 15 km and the fiber end at 25 km.](scattering_files/figure-html/fig-otdr-output-1.png){#fig-otdr width=727 height=448}\n:::\n:::\n\n\n## Worked example: Raman and Brillouin shifts (slides 284–288)\n\n::: {#338478b9 .cell execution_count=4}\n``` {.python .cell-code}\ndnu_R = 13.2e12\nfor lp in (1450, 1480):\n    print(f\"Raman pump at {lp} nm -> Stokes peak at {c0/(c0/nm(lp) - dnu_R)*1e9:.0f} nm\")\nvA, n_f = 5960, 1.45\nprint(f\"Brillouin shift at 1550 nm ≈ {2*n_f*vA/nm(1550)/1e9:.1f} GHz\")\nT = 298.15\nprint(f\"Raman anti-Stokes/Stokes thermometer sensitivity at 25 °C: h·Δν/(k_B T²) = {ol.h*dnu_R/(1.380649e-23*T**2)*100:.2f} %/K (slide 286: ≈ 0.8 %/K)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRaman pump at 1450 nm -> Stokes peak at 1549 nm\nRaman pump at 1480 nm -> Stokes peak at 1583 nm\nBrillouin shift at 1550 nm ≈ 11.2 GHz\nRaman anti-Stokes/Stokes thermometer sensitivity at 25 °C: h·Δν/(k_B T²) = 0.71 %/K (slide 286: ≈ 0.8 %/K)\n```\n:::\n:::\n\n\nA 1450 nm pump therefore amplifies the C band: this is distributed Raman amplification, one of the optical amplifiers of\nChapter 4. The Brillouin shift (≈ 11 GHz with bulk values; slightly lower in standard SMF because of the core doping) depends on\ntemperature and strain, which is the basis of distributed Brillouin sensing.\n\n## Beyond the Rayleigh limit: Mie scattering (optional package)\n\n::: {#cell-fig-mie .cell execution_count=5}\n``` {.python .cell-code}\ntry:\n    import miepython                           # pip install miepython (uses m = n − jκ, same convention as these notes)\n    d = np.logspace(-8, -5.5, 200)\n    qext, qsca, qback, g = miepython.efficiencies(1.5, d, nm(550), n_env=1.33)\n    x = np.pi*d*1.33/nm(550)\n    plt.loglog(x, qsca, label=\"Mie\"); plt.loglog(x, qsca[0]*(x/x[0])**4, \"--\", label=\"Rayleigh ∝ x⁴\")\n    plt.ylim(1e-8, 10); plt.xlabel(\"size parameter x = πd n_env/λ\"); plt.ylabel(\"Q_sca\"); plt.legend(); plt.show()\nexcept Exception as err:\n    print(\"miepython not available here:\", type(err).__name__)\n```\n\n::: {.cell-output .cell-output-display}\n![Scattering efficiency of a glass sphere in water versus size parameter (Mie theory). The Rayleigh law Q ∝ x⁴ holds only for x ≪ 1.](scattering_files/figure-html/fig-mie-output-1.png){#fig-mie width=731 height=426}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Going deeper\n- Why is the sky blue but clouds white? Use the Mie cell to find where the $\\lambda^{-4}$ law breaks down (size parameter $x\\sim1$).\n- OTDR dynamic range versus resolution: shorter pulses improve resolution but lower the backscattered energy. How do photon-counting\n  and coherent OTDRs (slide 283) get around this?\n- Distributed acoustic sensing (DAS) with phase-sensitive OTDR turns telecom fibers into kilometre-long microphone arrays. How is the\n  phase recovered?\n- Stimulated Brillouin scattering threshold: estimate it for 20 km of SMF with $P_{th}\\approx21A_\\text{eff}/(g_BL_\\text{eff})$.\n- Hollow-core fibers (NANF/DNANF) now reach losses comparable to or below solid-core fibers. Which scattering mechanism do they avoid?\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Complements\n- G. P. Agrawal, *Nonlinear Fiber Optics*: chapters on stimulated Raman and Brillouin scattering.\n- C. F. Bohren, D. R. Huffman, *Absorption and Scattering of Light by Small Particles*: Rayleigh and Mie theory.\n- A. H. Hartog, *An Introduction to Distributed Optical Fibre Sensors*, CRC Press: OTDR, Raman (DTS) and Brillouin sensing.\n:::\n\n## Try it yourself\n\n1. By how much does Rayleigh loss drop when moving from 850 nm to 1550 nm? Express it in dB over 2 km.\n2. The Raman shift is fixed in frequency. What pump wavelength amplifies the L-band (1590 nm)?\n3. A Brillouin sensor measures a shift of +5.5 MHz. Is that 100 µε of strain or 5 K of heating? (Use the coefficients of Chapter 2.)\n\n",
    "supporting": [
      "scattering_files"
    ],
    "filters": [],
    "includes": {}
  }
}