{
  "hash": "2542bd85d2da2f03ad54a433f3950321",
  "result": {
    "engine": "jupyter",
    "markdown": "# Antireflection coatings and thin-film optics {#sec-thinfilm}\n\n[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/{{< var github_user >}}/{{< var repo >}}/blob/main/{{< var subdir >}}/notebooks/thinfilm.ipynb){.colab-link} &nbsp;Run this chapter's code in Google Colab (no installation).\n\n\n*Slides 148–154 (antireflection coating of a solar cell) and slides 267–276 (multiple-beam thin-film interference, minimum and\nmaximum reflectance, transmission fringes of an a-Se film, incoherent multiple reflections in a plate).*\n\n## Key relations\n\nA film of index $n_2$ and thickness $d$ on a substrate $n_3$ reflects a sum of partial waves (slides 267–269). At normal\nincidence, with the round-trip phase $\\phi=2\\cdot\\frac{2\\pi}{\\lambda}n_2d$:\n\n$$\nr=\\frac{r_{12}+r_{23}e^{-j\\phi}}{1+r_{12}r_{23}e^{-j\\phi}},\\qquad r_{ij}=\\frac{n_i-n_j}{n_i+n_j}.\n$$\n\n| result | formula | slide |\n|---|---|---|\n| AR condition (phase) | $\\phi=m\\pi$, $m$ odd $\\Rightarrow d=m\\,\\dfrac{\\lambda}{4n_2}$ | 151–152, 270 |\n| AR condition (amplitude) | $n_2=\\sqrt{n_1n_3}$ so that $r_{12}=r_{23}$ | 153, 270 |\n| extreme reflectances ($n_1<n_2<n_3$) | $R_\\text{min}=\\left(\\dfrac{n_1n_3-n_2^2}{n_1n_3+n_2^2}\\right)^2$ at $\\phi=$ odd $\\pi$; $\\ R_\\text{max}=\\left(\\dfrac{n_3-n_1}{n_3+n_1}\\right)^2$ at $\\phi=$ even $\\pi$ | 272 |\n| incoherent plate | $T_\\text{plate}=(1-R)^2(1+R^2+R^4+\\dots)=\\dfrac{1-R}{1+R}$ | 276 |\n\nIf $n_1<n_3<n_2$ the expressions for $R_\\text{min}$ and $R_\\text{max}$ are interchanged (slide 272).\n\n### Thin-film designer, live\n\n```{ojs}\n//| echo: false\nviewof tf = Inputs.form({\n  n2: Inputs.range([1, 4], {value: 1.9, step: 0.01, label: \"film index n₂\"}),\n  n3: Inputs.range([1, 4], {value: 3.5, step: 0.01, label: \"substrate index n₃\"}),\n  d:  Inputs.range([0, 600], {value: 92, step: 1, label: \"film thickness d (nm)\"})\n})\n```\n\n```{ojs}\n//| echo: false\ntfData = {\n  const n1 = 1, r12 = (n1 - tf.n2) / (n1 + tf.n2), r23 = (tf.n2 - tf.n3) / (tf.n2 + tf.n3);\n  const out = [];\n  for (let l = 300; l <= 1200; l += 1) {\n    const phi = 4 * Math.PI * tf.n2 * tf.d / l, c = Math.cos(phi), s = Math.sin(phi);\n    // r = (r12 + r23 e^{-jφ}) / (1 + r12 r23 e^{-jφ})\n    const nr = r12 + r23 * c, ni = -r23 * s, dr = 1 + r12 * r23 * c, di = -r12 * r23 * s;\n    const R = (nr*nr + ni*ni) / (dr*dr + di*di);\n    out.push({l, R, q: \"with film\"}, {l, R: ((n1 - tf.n3)/(n1 + tf.n3))**2, q: \"bare substrate\"});\n  }\n  return out;\n}\nPlot.plot({\n  width: Math.min(width, 1050), height: 320, x: {label: \"λ (nm)\"}, y: {label: \"reflectance R\", domain: [0, Math.max(0.45, d3.max(tfData, d => d.R))], grid: true},\n  color: {legend: true, domain: [\"with film\", \"bare substrate\"], range: [\"#2a78d6\", \"#b9b8b2\"]},\n  marks: [Plot.rectX([{x1: 380, x2: 750}], {x1: \"x1\", x2: \"x2\", fill: \"#eda100\", fillOpacity: 0.07}),\n          Plot.line(tfData, {x: \"l\", y: \"R\", stroke: \"q\", strokeWidth: 2}),\n          Plot.tip(tfData.filter(d => d.q === \"with film\"), Plot.pointerX({x: \"l\", y: \"R\", title: d => `λ = ${d.l} nm\\nR = ${(100*d.R).toFixed(2)} %`}))]\n})\n```\n\n```{ojs}\n//| echo: false\n{\n  const n1 = 1, nideal = Math.sqrt(n1 * tf.n3);\n  const Rmin = ((n1*tf.n3 - tf.n2**2) / (n1*tf.n3 + tf.n2**2))**2;\n  const lmin = [1, 3, 5].map(m => 4 * tf.n2 * tf.d / m).filter(l => l >= 300 && l <= 1200);\n  return html`<div class=\"result-box\">ideal AR index √(n₁n₃) = ${nideal.toFixed(3)} · quarter-wave minima (R = ${(100*Rmin).toFixed(2)} %) at\n  ${lmin.length ? lmin.map(l => l.toFixed(0) + \" nm\").join(\", \") : \"none in range\"} · bare substrate R = ${(100*((n1-tf.n3)/(n1+tf.n3))**2).toFixed(1)} %\n  · shaded: visible</div>`\n}\n```\n\nWith the defaults (Si$_3$N$_4$ on silicon, $d=92$ nm) you get the solar-cell example below.\n\n## Worked example: antireflection coating on a silicon solar cell (slides 148–154)\n\n::: {#e47ad719 .cell execution_count=2}\n``` {.python .cell-code}\nR_si = ((1 - 3.5)/(1 + 3.5))**2\nprint(f\"bare Si (n = 3.5): R = {R_si:.1%}   → about 30 % of the light is lost (slide 149)\")\nprint(f\"ideal coating index √(1·3.5) = {np.sqrt(3.5):.2f}  (Si3N4, n ≈ 1.9, is a good choice)\")\nprint(f\"quarter-wave thickness at 700 nm: d = λ/(4 n2) = {700/(4*1.9):.1f} nm (or odd multiples)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbare Si (n = 3.5): R = 30.9%   → about 30 % of the light is lost (slide 149)\nideal coating index √(1·3.5) = 1.87  (Si3N4, n ≈ 1.9, is a good choice)\nquarter-wave thickness at 700 nm: d = λ/(4 n2) = 92.1 nm (or odd multiples)\n```\n:::\n:::\n\n\nA single quarter-wave layer is perfect only at one wavelength and only if $n_2=\\sqrt{n_1n_3}$ (slide 154). SiNₓ ($n\\approx2.0$) is\nthe industrial compromise. A dispersion-free $n_\\text{Si}=3.5$ is assumed here for clarity.\n\n::: {#cell-fig-ar-si .cell execution_count=3}\n``` {.python .cell-code}\nlam = np.linspace(nm(400), nm(1100), 700); l0, nSi = nm(700), 3.5\nfig, ax = plt.subplots()\nax.plot(lam*1e9, ol.tmm([1, nSi], [], lam)[0], color=ol.INK2, label=\"bare Si\")\nfor n2, lbl in ((np.sqrt(nSi), \"ideal n₂ = √3.5\"), (2.0, \"SiNₓ n₂ = 2.0\")):\n    ax.plot(lam*1e9, ol.tmm([1, n2, nSi], [l0/(4*n2)], lam)[0], label=f\"λ/4 {lbl}, d = {l0/(4*n2)*1e9:.0f} nm\")\nax.plot(lam*1e9, ol.tmm([1, 1.38, 2.3, nSi], [l0/(4*1.38), l0/(4*2.3)], lam)[0], \"--\", label=\"double layer 1.38 / 2.3\")\nax.set(xlabel=\"λ (nm)\", ylabel=\"R\", ylim=(0, 0.4)); ax.legend(fontsize=8); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Reflectance of silicon with single- and double-layer AR coatings designed for 700 nm (non-dispersive model).](thinfilm_files/figure-html/fig-ar-si-output-1.png){#fig-ar-si width=729 height=431}\n:::\n:::\n\n\n::: {#cell-fig-ar-real .cell execution_count=4}\n``` {.python .cell-code}\ntry:\n    from refractiveindex import RefractiveIndexMaterial\n    Si = RefractiveIndexMaterial(shelf=\"main\", book=\"Si\", page=\"Green-2008\")\n    lam_nm = np.linspace(400, 1100, 200)\n    N_Si = np.array([Si.get_refractive_index(l) - 1j*Si.get_extinction_coefficient(l) for l in lam_nm]).squeeze()\n    R = [ol.tmm([1, 2.0, Ni], [nm(700)/(4*2.0)], nm(l))[0][0] for Ni, l in zip(N_Si, lam_nm)]\n    Rb = [ol.tmm([1, Ni], [], nm(l))[0][0] for Ni, l in zip(N_Si, lam_nm)]\n    plt.plot(lam_nm, Rb, color=ol.INK2, label=\"bare c-Si\"); plt.plot(lam_nm, R, label=\"λ/4 SiNₓ at 700 nm\")\n    plt.xlabel(\"λ (nm)\"); plt.ylabel(\"R\"); plt.legend(); plt.show()\nexcept Exception as err:\n    print(\"refractiveindex package or database not available here:\", type(err).__name__)\n```\n\n::: {.cell-output .cell-output-display}\n![Same SiNx coating on crystalline silicon with measured dispersion and absorption (refractiveindex.info, Green 2008), if the optional package is available.](thinfilm_files/figure-html/fig-ar-real-output-1.png){#fig-ar-real width=719 height=425}\n:::\n:::\n\n\n## Worked example: a dielectric film on a semiconductor (slides 273–275)\n\n> A semiconductor ($n_3=3.5$) is coated with a 160 nm transparent film ($n_2=2.5$) in air. Find the minimum and maximum\n> reflectances and transmittances and their wavelengths in the visible.\n\n::: {#cell-fig-film .cell execution_count=5}\n``` {.python .cell-code}\nn1, n2, n3, d = 1.0, 2.5, 3.5, 160e-9\nRmin = ((n1*n3 - n2**2)/(n1*n3 + n2**2))**2\nRmax = ((n3 - n1)/(n3 + n1))**2\nprint(f\"R_min = {Rmin:.3f} → T_max = {1-Rmin:.0%};  R_max = {Rmax:.3f} → T_min = {1-Rmax:.0%}\")\nfor m in (1, 3):\n    print(f\"R_min (φ = {m}π) at λ = 4 n2 d / {m} = {4*n2*d/m*1e9:.0f} nm\")\nfor m in (1, 2, 3):\n    print(f\"R_max (φ = {2*m}π) at λ = 2 n2 d / {m} = {2*n2*d/m*1e9:.0f} nm\")\nlam = np.linspace(nm(350), nm(900), 1500)\nR = ol.tmm([n1, n2, n3], [d], lam)[0]\nfig, ax = plt.subplots(); ax.plot(lam*1e9, R, label=\"R\"); ax.plot(lam*1e9, 1 - R, \"--\", label=\"T\")\nfor l in (533.3e-9, 800e-9, 400e-9):\n    ax.plot(l*1e9, ol.tmm([n1, n2, n3], [d], l)[0][0], \"o\", color=ol.INK)\nax.set(xlabel=\"λ (nm)\", ylabel=\"R, T\"); ax.legend(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR_min = 0.080 → T_max = 92%;  R_max = 0.309 → T_min = 69%\nR_min (φ = 1π) at λ = 4 n2 d / 1 = 1600 nm\nR_min (φ = 3π) at λ = 4 n2 d / 3 = 533 nm\nR_max (φ = 2π) at λ = 2 n2 d / 1 = 800 nm\nR_max (φ = 4π) at λ = 2 n2 d / 2 = 400 nm\nR_max (φ = 6π) at λ = 2 n2 d / 3 = 267 nm\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Reflectance of a 160 nm film (n = 2.5) on n = 3.5 (slide 275). The dots mark the visible extrema.](thinfilm_files/figure-html/fig-film-output-2.png){#fig-film width=719 height=425}\n:::\n:::\n\n\nIn the visible, $R_\\text{min}$ (8 %) occurs at 533 nm and $R_\\text{max}$ (31 %) at 400 nm, which gives $T_\\text{max}=92\\,\\%$ and\n$T_\\text{min}=69\\,\\%$ as on slide 275.\n\n## Coherent and incoherent reflections (slides 274, 276)\n\nA thin film gives interference fringes (slide 274: transmission of an a-Se film on glass). A thick plate does not, because the\nsource's coherence length (@sec-coherence) is shorter than the round trip. Then intensities, not amplitudes, add:\n\n::: {#7130fa68 .cell execution_count=6}\n``` {.python .cell-code}\nRg = ((1.5 - 1)/(1.5 + 1))**2\nprint(f\"glass plate, incoherent multiple reflections: T = (1−R)/(1+R) = {(1-Rg)/(1+Rg):.4f}  \"\n      f\"(single surface 1−R = {1-Rg:.4f}, two surfaces without multiple reflections (1−R)² = {(1-Rg)**2:.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglass plate, incoherent multiple reflections: T = (1−R)/(1+R) = 0.9231  (single surface 1−R = 0.9600, two surfaces without multiple reflections (1−R)² = 0.9216)\n```\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Going deeper\n- The double-layer design above is illustrative. Optimise both thicknesses to minimise the solar-spectrum-weighted reflectance\n  (AM1.5G spectrum, `scipy.optimize`). What is gained versus texturing the surface?\n- Graded-index and moth-eye surfaces: why does a gradual index transition suppress reflection? Relate it to the limit of many thin layers.\n- Swanepoel's method (slide 274) extracts $n(\\lambda)$ and thickness of a film from the envelopes of its transmission fringes.\n  Implement it on a simulated spectrum from `ol.tmm`.\n- Facet coatings of semiconductor lasers and SOAs: AR (below $10^{-4}$) for amplifiers, HR for lasers. Estimate the tolerance on\n  thickness for a single-layer AR at 1550 nm.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Complements\n- Macleod, *Thin-Film Optical Filters*: design of AR, HR and band-pass coatings.\n- R. Swanepoel, \"Determination of the thickness and optical constants of amorphous silicon\", *J. Phys. E* 16, 1214 (1983).\n- M. A. Green, *Solar Cells: Operating Principles, Technology and System Applications*.\n:::\n\n## Try it yourself\n\n1. Use the live panel to design a single-layer AR for a glass lens ($n_3=1.52$) at 550 nm. Why is MgF₂ ($n=1.38$) used even though\n   it is not the ideal index?\n2. Why do soap bubbles show colours, and why does a soap film turn black just before it bursts?\n3. Find the thinnest film that makes a silicon surface look blue (minimum reflection in the red, maximum in the blue).\n\n",
    "supporting": [
      "thinfilm_files"
    ],
    "filters": [],
    "includes": {}
  }
}